# Generated by Django 3.1.12 on 2023-04-09 07:44

import User_login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('email', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
