# Generated by Django 3.2.18 on 2023-04-07 06:30

import Shop_db.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('product', djongo.models.fields.ArrayField(model_container=Shop_db.models.product)),
            ],
        ),
    ]
